### PR TITLE
shell script has been fixed

### PR DESCRIPTION
**Pull request by Ganther3301**

### CODE REVIEW

**Comment by Typeaway14** [comment]
Hey @Ganther3301, please remove the .o files and the executable file and only commit the `mktyrbo.sh` file. I'll accept the PR after that

**Comment by Ganther3301** [comment]
@Typeaway14 .o files and executable files are removed

**Comment by Typeaway14** [comment]
Thanks @Ganther3301 . Here's 5 bounty!

**Comment by Typeaway14** [comment]
!bounty 5

**Pull request closed without merging**
