### PR TITLE
BASKBETBALL MODE WORKS WITH NO INPUT OVERFLOW LESSGOOO

### PR DESCRIPTION
**Pull request by procub3r**
@Typeaway14 after literal 12 hours of work.
Now uses xmodmap to disable keys and setxkbmap to re-enable them.

### CODE REVIEW

**Comment by procub3r** [comment]
Issue #4 btw

**Comment by Typeaway14** [comment]
80 for the base and 20 brownie for the mad work that went into this. Job well done!

**Comment by Typeaway14** [comment]
!bounty 100

**Comment by procub3r** [comment]
lemme know if this is working on windows!
i'm pretty sure it will cause i didn't mess with anything inside an #ifdef _WIN32, but you never know 😄

**Comment by Typeaway14** [comment]
Hey @procub3r the code has _some_ issues with compilation. Nothing I can't fix on my side however :D

**Comment by Typeaway14** [comment]
!bounty 100

**Pull request merged**
