### PR TITLE
Update type_content.c fixed issue #13

### PR DESCRIPTION
**Pull request by TejasB02**

### CODE REVIEW

**Comment by Typeaway14** [comment]
Hi Tejas, You have not provided any explanation in your PR. I have clearly mentioned you need to explain the PR briefly. Kindly add a better description and then I can accept your PR @TejasB02

**Comment by Typeaway14** [comment]
Thanks for the help with documentation @TejasB02 !

**Comment by Typeaway14** [comment]
!bounty 45

**Comment by NavinShrinivas** [comment]
!bounty 55

**Pull request merged**
