### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by nik2203**
#8  Document the Baby Dragons

Added documentation for all four specified files.

PES2UG21CS334
Nikhil Girish

### CODE REVIEW

**Comment by nik2203** [comment]
Additional issue solved:
#5 Better test sentences
PES2UG21CS334
Nikhil Girish

**Comment by Typeaway14** [comment]
Cant merge this PR @nik2203. The quality of test sentences dont match the requirement :/

**Comment by nik2203** [comment]
hi, the pull request consisted of two issues but both were accidentally rejected as the latest one was rejected. Do I resubmit the PR of the earlier one (Documentation)?

**Comment by Typeaway14** [comment]
Hi @nik2203, thanks for bringing this to my notice, however, I just reviewed the documentation and that still seems to be inaccurate in certain places so I cannot merge this PR :/

**Pull request closed without merging**
